# Week 3b: Pandas — Data Analysis with Python

# Applied Statistics with Python (2026)

---

If NumPy is the **engine**, Pandas is the **dashboard**.  
Pandas gives you labeled, tabular data structures that make real-world data analysis fast and intuitive.

### What We'll Cover

| # | Topic |
|---|-------|
| 1 | Why Pandas? |
| 2 | Series — 1D Labeled Data |
| 3 | DataFrame — 2D Tabular Data |
| 4 | Reading & Writing Files |
| 5 | Data Inspection |
| 6 | Indexing & Selection |
| 7 | Data Manipulation |
| 8 | Handling Missing Data |
| 9 | GroupBy — Split-Apply-Combine |
| 10 | Merge & Concatenation |
| 11 | Apply & Lambda |
| 12 | Practical Example: Student Performance Analysis |

In [88]:
import numpy as np
import pandas as pd

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version:  {np.__version__}")

Pandas version: 2.2.2
NumPy version:  2.2.5

---
## 1. Why Pandas?

### NumPy Limitations

NumPy arrays are powerful but limited for real data analysis:

| Problem | NumPy | Pandas |
|---------|-------|--------|
| Column names | No — just index numbers | Yes — named columns |
| Mixed data types | No — all same dtype | Yes — each column can differ |
| Missing values | Limited (`np.nan`) | Rich support (`NaN`, `dropna`, `fillna`) |
| Data alignment | Manual | Automatic by label |
| File I/O | Basic | One-line CSV, Excel, SQL, JSON... |
| GroupBy / Pivot | Manual loops | Built-in methods |

### The Two Core Objects

| Object | Dimensions | Analogy |
|--------|------------|--------|
| **Series** | 1D | A single column in a spreadsheet |
| **DataFrame** | 2D | An entire spreadsheet / SQL table |

---
## 2. Series — 1D Labeled Data

A Series is like a NumPy array, but each element has a **label** (index).  
Think of it as a single column in a spreadsheet, with row labels on the left.

### 2.1 Creating a Series

Create a Series from a **list** — Pandas auto-generates integer indices (0, 1, 2, ...).

In [89]:
# From a list
scores = pd.Series([78, 92, 85, 67, 95])
print(scores)
print(f"\ntype: {type(scores)}")
print(f"dtype: {scores.dtype}")

0    78
1    92
2    85
3    67
4    95
dtype: int64

type: <class 'pandas.core.series.Series'>
dtype: int64

Create a Series with **custom labels** — much more informative for real data.

In [90]:
# With custom index
scores = pd.Series(
    [78, 92, 85, 67, 95],
    index=["Alice", "Bob", "Charlie", "Diana", "Eve"],
    name="Exam Score"
)
print(scores)

Alice      78
Bob        92
Charlie    85
Diana      67
Eve        95
Name: Exam Score, dtype: int64

Create a Series from a **dictionary** — keys become the index labels automatically.

In [91]:
# From a dictionary
gpa = pd.Series({
    "Alice": 3.8,
    "Bob": 3.2,
    "Charlie": 3.6,
    "Diana": 3.9,
})
print(gpa)

Alice      3.8
Bob        3.2
Charlie    3.6
Diana      3.9
dtype: float64

### 2.2 Series Indexing

You can access elements by **label** (like a dictionary) or by **position** (like a list).

In [5]:
scores = pd.Series(
    [78, 92, 85, 67, 95],
    index=["Alice", "Bob", "Charlie", "Diana", "Eve"]
)

# By label
print(f"By label: scores['Bob']    = {scores['Bob']}")
print(f"By label: scores[['Alice','Eve']] =\n{scores[['Alice','Eve']]}")

# By position
print(f"\nBy position: scores.iloc[0]  = {scores.iloc[0]}")
print(f"By position: scores.iloc[-1] = {scores.iloc[-1]}")

By label: scores['Bob']    = 92
By label: scores[['Alice','Eve']] =
Alice    78
Eve      95
dtype: int64

By position: scores.iloc[0]  = 78
By position: scores.iloc[-1] = 95

### 2.3 Series Operations

Like NumPy, operations are **vectorized** — they apply to every element automatically.

In [92]:
scores = pd.Series([78, 92, 85, 67, 95],
                    index=["Alice", "Bob", "Charlie", "Diana", "Eve"])

# Vectorized operations
print(f"Curved scores (add 5):\n{scores + 5}\n")

# Boolean filtering
print(f"Scores ≥ 85:\n{scores[scores >= 85]}\n")

# Built-in statistics
print(f"Mean:   {scores.mean():.1f}")
print(f"Std:    {scores.std():.1f}")
print(f"Median: {scores.median():.1f}")
print(f"Min:    {scores.min()}")
print(f"Max:    {scores.max()}")

Curved scores (add 5):
Alice       83
Bob         97
Charlie     90
Diana       72
Eve        100
dtype: int64

Scores ≥ 85:
Bob        92
Charlie    85
Eve        95
dtype: int64

Mean:   83.4
Std:    11.3
Median: 85.0
Min:    67
Max:    95

---
## 3. DataFrame — 2D Tabular Data

A DataFrame is the star of Pandas — a 2D table with **labeled rows and columns**.  
Think of it as:
- An Excel spreadsheet
- A SQL table
- A collection of Series that share the same index

### 3.1 Creating a DataFrame

**From a dictionary of lists** — each key becomes a column name, each list becomes column values.

In [93]:
# From a dictionary of lists
df = pd.DataFrame({
    "Name":   ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Age":    [22, 21, 23, 22, 20],
    "Major":  ["Data Science", "Statistics", "Math", "Data Science", "CS"],
    "GPA":    [3.8, 3.2, 3.6, 3.9, 3.5],
    "Score":  [92, 78, 85, 95, 88],
})
df

      Name  Age         Major  GPA  Score
0    Alice   22  Data Science  3.8     92
1      Bob   21    Statistics  3.2     78
2  Charlie   23          Math  3.6     85
3    Diana   22  Data Science  3.9     95
4      Eve   20            CS  3.5     88

**From a list of dictionaries** — each dictionary becomes a row.

In [94]:
# From a list of dictionaries
records = [
    {"Name": "Alice", "Age": 22, "Score": 92},
    {"Name": "Bob",   "Age": 21, "Score": 78},
    {"Name": "Charlie", "Age": 23, "Score": 85},
]
df2 = pd.DataFrame(records)
df2

      Name  Age  Score
0    Alice   22     92
1      Bob   21     78
2  Charlie   23     85

**From a NumPy array** — provide column names manually.

In [95]:
# From a NumPy array
rng = np.random.default_rng(42)
data = rng.integers(60, 100, size=(5, 3))

df3 = pd.DataFrame(data, columns=["Midterm", "Final", "Project"])
df3

   Midterm  Final  Project
0       63     90       86
1       77     77       94
2       63     87       68
3       63     81       99
4       89     90       88

---
## 4. Reading & Writing Files

Pandas can read and write many file formats in **one line of code**.  
No more manual parsing!

| Format | Read | Write |
|--------|------|-------|
| CSV | `pd.read_csv()` | `df.to_csv()` |
| Excel | `pd.read_excel()` | `df.to_excel()` |
| JSON | `pd.read_json()` | `df.to_json()` |
| SQL | `pd.read_sql()` | `df.to_sql()` |

### 4.1 Writing and Reading CSV

Let's create a sample dataset and save it to CSV.

In [96]:
# Create sample data
df = pd.DataFrame({
    "Name":    ["Alice", "Bob", "Charlie", "Diana", "Eve",
                "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "Age":     [22, 21, 23, 22, 20, 24, 21, 23, 22, 20],
    "Major":   ["DS", "Stats", "Math", "DS", "CS",
                "Stats", "Math", "DS", "CS", "Stats"],
    "Midterm": [85, 78, 92, 88, 76, 90, 82, 79, 95, 71],
    "Final":   [90, 82, 88, 95, 80, 85, 78, 88, 92, 75],
})

# Save to CSV
df.to_csv("students.csv", index=False)
print("Saved students.csv")
print(df)

Saved students.csv
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
4      Eve   20     CS       76     80
5    Frank   24  Stats       90     85
6    Grace   21   Math       82     78
7    Henry   23     DS       79     88
8      Ivy   22     CS       95     92
9     Jack   20  Stats       71     75

Read it back — `pd.read_csv()` handles parsing, type inference, and more.

In [ ]:
# Read CSV
df = pd.read_csv("students.csv")
print(f"Shape: {df.shape}")
df

### 4.2 Useful `read_csv()` Parameters

Real CSV files are often messy. These parameters help you handle common issues.

In [ ]:
# Common read_csv parameters (not all need to be used at once)

# df = pd.read_csv("file.csv",
#     sep=",",           # Delimiter (default comma; use "\t" for TSV)
#     header=0,          # Row number for column names (0 = first row)
#     index_col=0,       # Column to use as row index
#     usecols=["A","B"], # Only read these columns
#     nrows=100,         # Only read first 100 rows
#     skiprows=5,        # Skip first 5 rows
#     na_values=["NA", "?", "-"],  # Treat these as missing
#     encoding="utf-8",  # File encoding
#     dtype={"ID": str}, # Force column types
# )

print("See comments above for common read_csv parameters")

### 4.3 Writing and Reading Excel

Excel is the most common data format in business and academia. Pandas handles it natively.

> **Note:** You may need to install `openpyxl` first: `pip install openpyxl`

**Write a DataFrame to Excel** — use `to_excel()`. Each DataFrame becomes one sheet.

In [97]:
# Write DataFrame to a single-sheet Excel file
df = pd.read_csv("students.csv")
df.to_excel("students.xlsx", index=False, sheet_name="Sheet1")
print("Saved students.xlsx")
print(df.head())

Saved students.xlsx
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
4      Eve   20     CS       76     80

**Read an Excel file** — `pd.read_excel()` works just like `read_csv()`. By default it reads the first sheet.

In [ ]:
# Read the Excel file back
df_excel = pd.read_excel("students.xlsx")
print(f"Shape: {df_excel.shape}")
df_excel.head()

**Write multiple sheets** to one Excel file — use `ExcelWriter` as a context manager. This is like having multiple tabs in one workbook.

In [98]:
# Write multiple sheets to one Excel file
df = pd.read_csv("students.csv")

# Split data by major
ds_students = df[df["Major"] == "DS"]
stats_students = df[df["Major"] == "Stats"]
math_students = df[df["Major"] == "Math"]

# Write each group to a separate sheet using ExcelWriter
with pd.ExcelWriter("students_by_major.xlsx") as writer:
    df.to_excel(writer, sheet_name="All Students", index=False)
    ds_students.to_excel(writer, sheet_name="Data Science", index=False)
    stats_students.to_excel(writer, sheet_name="Statistics", index=False)
    math_students.to_excel(writer, sheet_name="Mathematics", index=False)

print("Saved students_by_major.xlsx with 4 sheets")

Saved students_by_major.xlsx with 4 sheets

**Read a specific sheet** — use `sheet_name` to choose which tab to read. You can also read all sheets at once into a dictionary.

In [101]:
# Read a specific sheet by name
df_ds = pd.read_excel("students_by_major.xlsx", sheet_name="Data Science")
print("--- Data Science sheet ---")
print(df_ds)

# Read a specific sheet by index (0 = first sheet)
df_first = pd.read_excel("students_by_major.xlsx", sheet_name=0)
print(f"\n--- First sheet (All Students): {len(df_first)} rows ---")

# Read ALL sheets at once → returns a dict of DataFrames
all_sheets = pd.read_excel("students_by_major.xlsx", sheet_name=None)
print(f"\nAll sheet names: {list(all_sheets.keys())}")
for name, sheet_df in all_sheets.items():
    print(f"  {name}: {sheet_df.shape}")

--- Data Science sheet ---
    Name  Age Major  Midterm  Final
0  Alice   22    DS       85     90
1  Diana   22    DS       88     95
2  Henry   23    DS       79     88

--- First sheet (All Students): 10 rows ---

All sheet names: ['All Students', 'Data Science', 'Statistics', 'Mathematics']
  All Students: (10, 5)
  Data Science: (3, 5)
  Statistics: (3, 5)
  Mathematics: (2, 5)

### 4.4 Useful `read_csv()` / `read_excel()` / `read_json()` Parameters

These three functions share many common parameters (`header`, `usecols`, `skiprows`, `nrows`, `dtype`, etc.), 
but each also has format-specific options. Let's see them **in action** with real data.

#### `read_csv()` — Common Parameters in Action

In [20]:
# ---- read_csv(): Common Parameters Demo ----

# 1) Basic read — row 0 is used as column header by default
df_basic = pd.read_csv("students.csv")
print("=== 1. Basic read ===")
print(df_basic)
print()

=== 1. Basic read ===
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
4      Eve   20     CS       76     80
5    Frank   24  Stats       90     85
6    Grace   21   Math       82     78
7    Henry   23     DS       79     88
8      Ivy   22     CS       95     92
9     Jack   20  Stats       71     75

In [102]:
# 2) usecols — read only specific columns (saves memory on large files)
df_cols = pd.read_csv("students.csv", usecols=["Name", "Major", "Final"])
print("=== 2. usecols: only Name, Major, Final ===")
print(df_cols)
print()

=== 2. usecols: only Name, Major, Final ===
      Name  Major  Final
0    Alice     DS     90
1      Bob  Stats     82
2  Charlie   Math     88
3    Diana     DS     95
4      Eve     CS     80
5    Frank  Stats     85
6    Grace   Math     78
7    Henry     DS     88
8      Ivy     CS     92
9     Jack  Stats     75

In [22]:
# 3) index_col — use a column as the row index
df_idx = pd.read_csv("students.csv", index_col="Name")
print("=== 3. index_col: use Name as row index ===")
print(df_idx)
print()

=== 3. index_col: use Name as row index ===
         Age  Major  Midterm  Final
Name
Alice     22     DS       85     90
Bob       21  Stats       78     82
Charlie   23   Math       92     88
Diana     22     DS       88     95
Eve       20     CS       76     80
Frank     24  Stats       90     85
Grace     21   Math       82     78
Henry     23     DS       79     88
Ivy       22     CS       95     92
Jack      20  Stats       71     75

In [103]:
# 4) nrows — read only the first N rows (great for previewing large files)
df_head = pd.read_csv("students.csv", nrows=3)
print("=== 4. nrows=3: only first 3 rows ===")
print(df_head)
print()

=== 4. nrows=3: only first 3 rows ===
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88

In [24]:
# 5) skiprows — skip specific rows (accepts int or list)
df_skip = pd.read_csv("students.csv", skiprows=[1, 3])  # skip row 1 (Alice) and row 3 (Charlie)
print("=== 5. skiprows=[1,3]: skip Alice and Charlie ===")
print(df_skip)
print()

=== 5. skiprows=[1,3]: skip Alice and Charlie ===
    Name  Age  Major  Midterm  Final
0    Bob   21  Stats       78     82
1  Diana   22     DS       88     95
2    Eve   20     CS       76     80
3  Frank   24  Stats       90     85
4  Grace   21   Math       82     78
5  Henry   23     DS       79     88
6    Ivy   22     CS       95     92
7   Jack   20  Stats       71     75

In [25]:
# 6) dtype — force column data types
#    e.g., keep Age as string instead of int
df_dtype = pd.read_csv("students.csv", dtype={"Age": str, "Midterm": float})
print("=== 6. dtype: Age->str, Midterm->float ===")
print(df_dtype.dtypes)
print()
print(df_dtype.head(3))

=== 6. dtype: Age->str, Midterm->float ===
Name        object
Age         object
Major       object
Midterm    float64
Final        int64
dtype: object

      Name Age  Major  Midterm  Final
0    Alice  22     DS     85.0     90
1      Bob  21  Stats     78.0     82
2  Charlie  23   Math     92.0     88

In [26]:
# 7) na_values — specify which strings should be treated as NaN
#    Let's create a small CSV with messy missing-value markers
import io

csv_with_na = """Name,Age,Major,Midterm,Final
Alice,22,DS,85,90
Bob,N/A,Stats,--,82
Charlie,23,Math,92,missing"""

df_na = pd.read_csv(io.StringIO(csv_with_na), na_values=["N/A", "--", "missing"])
print("=== 7. na_values: treat N/A, --, missing as NaN ===")
print(df_na)
print(f"\nMissing value count per column:\n{df_na.isna().sum()}")

=== 7. na_values: treat N/A, --, missing as NaN ===
      Name   Age  Major  Midterm  Final
0    Alice  22.0     DS     85.0   90.0
1      Bob   NaN  Stats      NaN   82.0
2  Charlie  23.0   Math     92.0    NaN

Missing value count per column:
Name       0
Age        1
Major      0
Midterm    1
Final      1
dtype: int64

#### `read_excel()` — Common Parameters in Action

`read_excel()` supports most of the same parameters as `read_csv()`, **plus** Excel-specific ones like `sheet_name` and column-letter `usecols`.

In [104]:
# ---- read_excel(): Common Parameters Demo ----

# 1) Basic read — reads the first sheet by default
df_xl = pd.read_excel("students.xlsx")
print("=== 1. Basic Excel read ===")
print(df_xl)
print()

=== 1. Basic Excel read ===
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
4      Eve   20     CS       76     80
5    Frank   24  Stats       90     85
6    Grace   21   Math       82     78
7    Henry   23     DS       79     88
8      Ivy   22     CS       95     92
9     Jack   20  Stats       71     75

In [28]:
# 2) sheet_name — select which worksheet to read (Excel-specific!)
#    Can be a name (str), index (int), or None (all sheets)

# By name
df_sheet = pd.read_excel("students_by_major.xlsx", sheet_name="Statistics")
print("=== 2a. sheet_name='Statistics' ===")
print(df_sheet)
print()

# By index (0 = first sheet)
df_first = pd.read_excel("students_by_major.xlsx", sheet_name=0)
print(f"=== 2b. sheet_name=0 (first sheet): {len(df_first)} rows ===")
print(df_first.head(3))
print()

# None = read ALL sheets → returns a dict of DataFrames
all_sheets = pd.read_excel("students_by_major.xlsx", sheet_name=None)
print("=== 2c. sheet_name=None (all sheets) ===")
for name, sdf in all_sheets.items():
    print(f"  {name}: {sdf.shape}")

=== 2a. sheet_name='Statistics' ===
    Name  Age  Major  Midterm  Final
0    Bob   21  Stats       78     82
1  Frank   24  Stats       90     85
2   Jack   20  Stats       71     75

=== 2b. sheet_name=0 (first sheet): 10 rows ===
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88

=== 2c. sheet_name=None (all sheets) ===
  All Students: (10, 5)
  Data Science: (3, 5)
  Statistics: (3, 5)
  Mathematics: (2, 5)

In [105]:
# 3) usecols — Excel supports column-letter ranges like "A:C" (Excel-specific!)
df_xl_cols = pd.read_excel("students.xlsx", usecols="A:C")  # columns A, B, C only
print("=== 3a. usecols='A:C': first 3 columns ===")
print(df_xl_cols)
print()

# Also works with column name lists (same as read_csv)
df_xl_cols2 = pd.read_excel("students.xlsx", usecols=["Name", "Final"])
print("=== 3b. usecols=['Name','Final'] ===")
print(df_xl_cols2)

=== 3a. usecols='A:C': first 3 columns ===
      Name  Age  Major
0    Alice   22     DS
1      Bob   21  Stats
2  Charlie   23   Math
3    Diana   22     DS
4      Eve   20     CS
5    Frank   24  Stats
6    Grace   21   Math
7    Henry   23     DS
8      Ivy   22     CS
9     Jack   20  Stats

=== 3b. usecols=['Name','Final'] ===
      Name  Final
0    Alice     90
1      Bob     82
2  Charlie     88
3    Diana     95
4      Eve     80
5    Frank     85
6    Grace     78
7    Henry     88
8      Ivy     92
9     Jack     75

In [30]:
# 4) skiprows + nrows — skip rows and limit row count (same as read_csv)
df_xl_skip = pd.read_excel("students.xlsx", skiprows=2, nrows=3)
print("=== 4. skiprows=2, nrows=3 ===")
print(df_xl_skip)
print()

# 5) dtype — force column types (same as read_csv)
df_xl_dtype = pd.read_excel("students.xlsx", dtype={"Age": str})
print("=== 5. dtype: Age->str ===")
print(df_xl_dtype.dtypes)

=== 4. skiprows=2, nrows=3 ===
       Bob  21 Stats  78  82
0  Charlie  23  Math  92  88
1    Diana  22    DS  88  95
2      Eve  20    CS  76  80

=== 5. dtype: Age->str ===
Name       object
Age        object
Major      object
Midterm     int64
Final       int64
dtype: object

#### `read_json()` — Reading JSON Data

JSON (JavaScript Object Notation) is the most common data format for Web APIs. Pandas can read and write JSON directly.

In [106]:
# ---- First, create a JSON file from our CSV data ----

df = pd.read_csv("students.csv")

# orient="records": each row becomes a dict — the most common API format
# [{"Name":"Alice","Age":22,...}, {"Name":"Bob",...}]
df.to_json("students.json", orient="records", indent=2, force_ascii=False)

print("students.json created! Preview:")
with open("students.json") as f:
    print(f.read())

students.json created! Preview:
[
  {
    "Name":"Alice",
    "Age":22,
    "Major":"DS",
    "Midterm":85,
    "Final":90
  },
  {
    "Name":"Bob",
    "Age":21,
    "Major":"Stats",
    "Midterm":78,
    "Final":82
  },
  {
    "Name":"Charlie",
    "Age":23,
    "Major":"Math",
    "Midterm":92,
    "Final":88
  },
  {
    "Name":"Diana",
    "Age":22,
    "Major":"DS",
    "Midterm":88,
    "Final":95
  },
  {
    "Name":"Eve",
    "Age":20,
    "Major":"CS",
    "Midterm":76,
    "Final":80
  },
  {
    "Name":"Frank",
    "Age":24,
    "Major":"Stats",
    "Midterm":90,
    "Final":85
  },
  {
    "Name":"Grace",
    "Age":21,
    "Major":"Math",
    "Midterm":82,
    "Final":78
  },
  {
    "Name":"Henry",
    "Age":23,
    "Major":"DS",
    "Midterm":79,
    "Final":88
  },
  {
    "Name":"Ivy",
    "Age":22,
    "Major":"CS",
    "Midterm":95,
    "Final":92
  },
  {
    "Name":"Jack",
    "Age":20,
    "Major":"Stats",
    "Midterm":71,
    "Final":75
  }
]

In [32]:
# ---- read_json(): Common Parameters Demo ----

# 1) Basic read — orient must match how the file was written
df_json = pd.read_json("students.json", orient="records")
print("=== 1. Basic JSON read (orient='records') ===")
print(df_json)
print()

=== 1. Basic JSON read (orient='records') ===
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
4      Eve   20     CS       76     80
5    Frank   24  Stats       90     85
6    Grace   21   Math       82     78
7    Henry   23     DS       79     88
8      Ivy   22     CS       95     92
9     Jack   20  Stats       71     75

In [33]:
# 2) orient — different JSON structures (JSON-specific!)
#    'records' : [{col:val, ...}, ...]       ← most common (API responses)
#    'columns' : {col: {idx:val, ...}, ...}  ← organized by column
#    'index'   : {idx: {col:val, ...}, ...}  ← organized by row index
#    'split'   : {columns:[...], data:[...]}  ← columns and data separated

df_small = df.head(3)

for orient in ["records", "columns", "index", "split"]:
    json_str = df_small.to_json(orient=orient, indent=2)
    print(f'=== orient="{orient}" ===')
    print(json_str[:200])  # show first 200 chars
    print()

=== orient="records" ===
[
  {
    "Name":"Alice",
    "Age":22,
    "Major":"DS",
    "Midterm":85,
    "Final":90
  },
  {
    "Name":"Bob",
    "Age":21,
    "Major":"Stats",
    "Midterm":78,
    "Final":82
  },
  {
    "

=== orient="columns" ===
{
  "Name":{
    "0":"Alice",
    "1":"Bob",
    "2":"Charlie"
  },
  "Age":{
    "0":22,
    "1":21,
    "2":23
  },
  "Major":{
    "0":"DS",
    "1":"Stats",
    "2":"Math"
  },
  "Midterm":{
    "

=== orient="index" ===
{
  "0":{
    "Name":"Alice",
    "Age":22,
    "Major":"DS",
    "Midterm":85,
    "Final":90
  },
  "1":{
    "Name":"Bob",
    "Age":21,
    "Major":"Stats",
    "Midterm":78,
    "Final":82
  },


=== orient="split" ===
{
  "columns":[
    "Name",
    "Age",
    "Major",
    "Midterm",
    "Final"
  ],
  "index":[
    0,
    1,
    2
  ],
  "data":[
    [
      "Alice",
      22,
      "DS",
      85,
      90
    ],

In [41]:
# 3) dtype — force column types (same as read_csv / read_excel)
df_json_dtype = pd.read_json("students.json", orient="records", dtype={"Age": str})
print("=== 3. dtype: Age->str ===")
print(df_json_dtype.dtypes)
print()
print(df_json_dtype.head(3))

=== 3. dtype: Age->str ===
Name       object
Age        object
Major      object
Midterm     int64
Final       int64
dtype: object

      Name Age  Major  Midterm  Final
0    Alice  22     DS       85     90
1      Bob  21  Stats       78     82
2  Charlie  23   Math       92     88

In [107]:
# 4) Read JSON from a string (no file needed)
#    Useful when working with Web API responses
import io

json_string = '[{"city":"Beijing","temp":32},{"city":"Shanghai","temp":35},{"city":"Guangzhou","temp":33}]'

df_api = pd.read_json(io.StringIO(json_string), orient="records")
print("=== 4. Read from JSON string (simulating API response) ===")
print(df_api)

=== 4. Read from JSON string (simulating API response) ===
        city  temp
0    Beijing    32
1   Shanghai    35
2  Guangzhou    33

#### Parameter Comparison Table

| Parameter | `read_csv()` | `read_excel()` | `read_json()` |
|-----------|:---:|:---:|:---:|
| `header` | ✅ | ✅ | ❌ |
| `index_col` | ✅ | ✅ | ❌ |
| `usecols` | ✅ | ✅ (supports `"A:D"`) | ❌ |
| `skiprows` | ✅ | ✅ | ❌ |
| `nrows` | ✅ | ✅ | ✅ |
| `dtype` | ✅ | ✅ | ✅ |
| `na_values` | ✅ | ✅ | ❌ |
| `sheet_name` | ❌ | ✅ | ❌ |
| `orient` | ❌ | ❌ | ✅ |
| `encoding` | ✅ | ❌ | ✅ |

---
## 5. Data Inspection

The first thing you do with any dataset: **look at it**. Pandas provides many methods for quick exploration.

### 5.1 Quick Look

`head()` and `tail()` show the first/last rows — always start here.

In [108]:
df = pd.read_csv("students.csv")

# First 3 rows
print("--- head(3) ---")
print(df.head(3))

# Last 3 rows
print("\n--- tail(3) ---")
print(df.tail(3))

--- head(3) ---
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
1      Bob   21  Stats       78     82
2  Charlie   23   Math       92     88

--- tail(3) ---
    Name  Age  Major  Midterm  Final
7  Henry   23     DS       79     88
8    Ivy   22     CS       95     92
9   Jack   20  Stats       71     75

`shape`, `columns`, and `dtypes` give you the structural overview.

In [109]:
print(f"Shape:   {df.shape}  ({df.shape[0]} rows × {df.shape[1]} columns)")
print(f"Columns: {list(df.columns)}")
print(f"\nData types:\n{df.dtypes}")

Shape:   (10, 5)  (10 rows × 5 columns)
Columns: ['Name', 'Age', 'Major', 'Midterm', 'Final']

Data types:
Name       object
Age         int64
Major      object
Midterm     int64
Final       int64
dtype: object

### 5.2 `info()` and `describe()`

`info()` shows the **structure** (column names, types, non-null counts, memory).  
`describe()` shows the **summary statistics** of numeric columns.

In [110]:
# Structural overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Age      10 non-null     int64
 2   Major    10 non-null     object
 3   Midterm  10 non-null     int64
 4   Final    10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

`describe()` gives count, mean, std, min, 25%, 50%, 75%, max for every numeric column — the **five-number summary** plus extras.

In [111]:
# Statistical summary
df.describe()

             Age    Midterm      Final
count  10.000000  10.000000  10.000000
mean   21.800000  83.600000  85.300000
std     1.316561   7.705698   6.447222
min    20.000000  71.000000  75.000000
25%    21.000000  78.250000  80.500000
50%    22.000000  83.500000  86.500000
75%    22.750000  89.500000  89.500000
max    24.000000  95.000000  95.000000

`value_counts()` shows the frequency of each unique value — essential for categorical columns.

In [112]:
# Value counts for categorical columns
print("--- Major distribution ---")
print(df["Major"].value_counts())

print("\n--- Age distribution ---")
print(df["Age"].value_counts().sort_index())

--- Major distribution ---
Major
DS       3
Stats    3
Math     2
CS       2
Name: count, dtype: int64

--- Age distribution ---
Age
20    2
21    2
22    3
23    2
24    1
Name: count, dtype: int64

---
## 6. Indexing & Selection

Selecting data is the most common operation in Pandas. There are several methods:

| Method | Selects by | Example |
|--------|-----------|--------|
| `df["col"]` | Column name | `df["Age"]` |
| `df[["A","B"]]` | Multiple columns | `df[["Name","Score"]]` |
| `df.loc[row, col]` | Labels | `df.loc[0, "Name"]` |
| `df.iloc[row, col]` | Integer positions | `df.iloc[0, 0]` |
| `df[condition]` | Boolean mask | `df[df["Age"] > 21]` |

### 6.1 Selecting Columns

Select a **single column** (returns a Series) or **multiple columns** (returns a DataFrame).

In [113]:
# Single column → Series
print(type(df["Name"]))
print(df["Name"])

print("\n--- Multiple columns → DataFrame ---")
print(df[["Name", "Midterm", "Final"]])

<class 'pandas.core.series.Series'>
0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
5      Frank
6      Grace
7      Henry
8        Ivy
9       Jack
Name: Name, dtype: object

--- Multiple columns → DataFrame ---
      Name  Midterm  Final
0    Alice       85     90
1      Bob       78     82
2  Charlie       92     88
3    Diana       88     95
4      Eve       76     80
5    Frank       90     85
6    Grace       82     78
7    Henry       79     88
8      Ivy       95     92
9     Jack       71     75

### 6.2 `loc` — Label-Based Selection

Use `loc[row_label, col_label]` to select by **labels**. Both row and column can be single labels, lists, or slices.

In [49]:
# loc: label-based
print("Single element:")
print(f"  df.loc[0, 'Name'] = {df.loc[0, 'Name']}")

print("\nSingle row:")
print(df.loc[0])

print("\nRows 0-2, specific columns:")
print(df.loc[0:2, ["Name", "Midterm", "Final"]])

Single element:
  df.loc[0, 'Name'] = Alice

Single row:
Name       Alice
Age           22
Major         DS
Midterm       85
Final         90
Name: 0, dtype: object

Rows 0-2, specific columns:
      Name  Midterm  Final
0    Alice       85     90
1      Bob       78     82
2  Charlie       92     88

### 6.3 `iloc` — Integer Position-Based Selection

Use `iloc[row_pos, col_pos]` to select by **integer positions**. Works like NumPy indexing.

In [114]:
# iloc: position-based
print(f"First row, first col: {df.iloc[0, 0]}")
print(f"Last row:  {df.iloc[-1].to_dict()}")

print("\nFirst 3 rows, columns 0 and 3:")
print(df.iloc[:3, [0, 3]])

First row, first col: Alice
Last row:  {'Name': 'Jack', 'Age': 20, 'Major': 'Stats', 'Midterm': 71, 'Final': 75}

First 3 rows, columns 0 and 3:
      Name  Midterm
0    Alice       85
1      Bob       78
2  Charlie       92

### 6.4 Boolean Indexing (Filtering)

The most powerful selection method — use **conditions** to filter rows. This is how you'll select data in practice.

In [115]:
df = pd.read_csv("students.csv")

# Single condition
print("--- Students with Midterm ≥ 85 ---")
print(df[df["Midterm"] >= 85])

# Multiple conditions (use & for AND, | for OR, ~ for NOT)
print("\n--- DS majors with Final ≥ 85 ---")
print(df[(df["Major"] == "DS") & (df["Final"] >= 85)])

--- Students with Midterm ≥ 85 ---
      Name  Age  Major  Midterm  Final
0    Alice   22     DS       85     90
2  Charlie   23   Math       92     88
3    Diana   22     DS       88     95
5    Frank   24  Stats       90     85
8      Ivy   22     CS       95     92

--- DS majors with Final ≥ 85 ---
    Name  Age Major  Midterm  Final
0  Alice   22    DS       85     90
3  Diana   22    DS       88     95
7  Henry   23    DS       79     88

The `isin()` method checks if values are in a given list — great for filtering by multiple categories.

In [116]:
# isin() for multiple values
print("--- DS or Stats majors ---")
print(df[df["Major"].isin(["DS", "Stats"])])

--- DS or Stats majors ---
    Name  Age  Major  Midterm  Final
0  Alice   22     DS       85     90
1    Bob   21  Stats       78     82
3  Diana   22     DS       88     95
5  Frank   24  Stats       90     85
7  Henry   23     DS       79     88
9   Jack   20  Stats       71     75

The `query()` method lets you write conditions as a **string** — more readable for complex filters.

In [ ]:
# query() — more readable for complex filters
print("--- query: Age >= 22 and Midterm >= 85 ---")
print(df.query("Age >= 22 and Midterm >= 85"))

### 6.5 `between()` — Range Filtering

`between(low, high)` is a shortcut for `(col >= low) & (col <= high)` — cleaner and more readable.

In [53]:
# between() — inclusive range filter
print("--- Midterm between 80 and 90 ---")
print(df[df["Midterm"].between(80, 90)])

# Combine with other conditions
print("\n--- Age 21-22 AND Midterm 80-95 ---")
mask = df["Age"].between(21, 22) & df["Midterm"].between(80, 95)
print(df[mask][["Name", "Age", "Midterm"]])

--- Midterm between 80 and 90 ---
    Name  Age  Major  Midterm  Final
0  Alice   22     DS       85     90
3  Diana   22     DS       88     95
5  Frank   24  Stats       90     85
6  Grace   21   Math       82     78

--- Age 21-22 AND Midterm 80-95 ---
    Name  Age  Midterm
0  Alice   22       85
3  Diana   22       88
6  Grace   21       82
8    Ivy   22       95

---
## 7. Data Manipulation

Transforming, adding, and removing columns is how you prepare data for analysis.

### 7.1 Adding New Columns

Add a calculated column — this is **vectorized**, so it runs on the entire column at once.

In [117]:
df = pd.read_csv("students.csv")

# Calculated column: weighted average
df["Average"] = df["Midterm"] * 0.4 + df["Final"] * 0.6

# Conditional column using np.select()
conditions = [
    df["Average"] >= 90,
    df["Average"] >= 80,
    df["Average"] >= 70,
    df["Average"] >= 60,
]
grades = ["A", "B", "C", "D"]
df["Grade"] = np.select(conditions, grades, default="F")

print(df[["Name", "Midterm", "Final", "Average", "Grade"]])

      Name  Midterm  Final  Average Grade
0    Alice       85     90     88.0     B
1      Bob       78     82     80.4     B
2  Charlie       92     88     89.6     B
3    Diana       88     95     92.2     A
4      Eve       76     80     78.4     C
5    Frank       90     85     87.0     B
6    Grace       82     78     79.6     C
7    Henry       79     88     84.4     B
8      Ivy       95     92     93.2     A
9     Jack       71     75     73.4     C

### 7.2 Renaming Columns

In [118]:
# Rename specific columns
df_renamed = df.rename(columns={"Midterm": "Mid", "Final": "Fin"})
print(f"Columns: {list(df_renamed.columns)}")

# Lowercase all columns
df_lower = df.rename(columns=str.lower)
print(f"Lowercase: {list(df_lower.columns)}")

Columns: ['Name', 'Age', 'Major', 'Mid', 'Fin', 'Average', 'Grade']
Lowercase: ['name', 'age', 'major', 'midterm', 'final', 'average', 'grade']

### 7.3 Dropping Columns and Rows

In [119]:
# Drop columns
df_slim = df.drop(columns=["Grade"])
print(f"After dropping 'Grade': {list(df_slim.columns)}")

# Drop rows by index
df_fewer = df.drop(index=[0, 1])
print(f"\nAfter dropping rows 0,1: {len(df_fewer)} rows remaining")
print(df_fewer.head())

After dropping 'Grade': ['Name', 'Age', 'Major', 'Midterm', 'Final', 'Average']

After dropping rows 0,1: 8 rows remaining
      Name  Age  Major  Midterm  Final  Average Grade
2  Charlie   23   Math       92     88     89.6     B
3    Diana   22     DS       88     95     92.2     A
4      Eve   20     CS       76     80     78.4     C
5    Frank   24  Stats       90     85     87.0     B
6    Grace   21   Math       82     78     79.6     C

### 7.4 Sorting

Sort by one or more columns — use `ascending=False` for descending order.

In [57]:
# Sort by single column
print("--- Sorted by Average (descending) ---")
print(df.sort_values("Average", ascending=False)[["Name", "Average", "Grade"]])

# Sort by multiple columns
print("\n--- Sorted by Grade (asc), then Average (desc) ---")
print(df.sort_values(["Grade", "Average"], ascending=[True, False])[["Name", "Average", "Grade"]])

--- Sorted by Average (descending) ---
      Name  Average Grade
8      Ivy     93.2     A
3    Diana     92.2     A
2  Charlie     89.6     B
0    Alice     88.0     B
5    Frank     87.0     B
7    Henry     84.4     B
1      Bob     80.4     B
6    Grace     79.6     C
4      Eve     78.4     C
9     Jack     73.4     C

--- Sorted by Grade (asc), then Average (desc) ---
      Name  Average Grade
8      Ivy     93.2     A
3    Diana     92.2     A
2  Charlie     89.6     B
0    Alice     88.0     B
5    Frank     87.0     B
7    Henry     84.4     B
1      Bob     80.4     B
6    Grace     79.6     C
4      Eve     78.4     C
9     Jack     73.4     C

### 7.5 `nlargest()` and `nsmallest()` — Quick Top/Bottom N

In [58]:
# Top 3 students by average
print("--- Top 3 ---")
print(df.nlargest(3, "Average")[["Name", "Average", "Grade"]])

# Bottom 3 students by average
print("\n--- Bottom 3 ---")
print(df.nsmallest(3, "Average")[["Name", "Average", "Grade"]])

--- Top 3 ---
      Name  Average Grade
8      Ivy     93.2     A
3    Diana     92.2     A
2  Charlie     89.6     B

--- Bottom 3 ---
    Name  Average Grade
9   Jack     73.4     C
4    Eve     78.4     C
6  Grace     79.6     C

### 7.6 String Methods (`.str`)

Pandas provides a `.str` accessor for **vectorized string operations** on text columns — no loops needed.

In [59]:
df = pd.read_csv("students.csv")

# Convert to uppercase / lowercase
print("--- Upper case ---")
print(df["Name"].str.upper())

# Check if string contains a substring
print("\n--- Names containing 'a' (case-insensitive) ---")
print(df[df["Name"].str.lower().str.contains("a")]["Name"])

# Get string length
print("\n--- Name lengths ---")
df["Name_Len"] = df["Name"].str.len()
print(df[["Name", "Name_Len"]])

# Slice strings (first 3 characters)
print("\n--- First 3 chars ---")
print(df["Name"].str[:3])

--- Upper case ---
0      ALICE
1        BOB
2    CHARLIE
3      DIANA
4        EVE
5      FRANK
6      GRACE
7      HENRY
8        IVY
9       JACK
Name: Name, dtype: object

--- Names containing 'a' (case-insensitive) ---
0      Alice
2    Charlie
3      Diana
5      Frank
6      Grace
9       Jack
Name: Name, dtype: object

--- Name lengths ---
      Name  Name_Len
0    Alice         5
1      Bob         3
2  Charlie         7
3    Diana         5
4      Eve         3
5    Frank         5
6    Grace         5
7    Henry         5
8      Ivy         3
9     Jack         4

--- First 3 chars ---
0    Ali
1    Bob
2    Cha
3    Dia
4    Eve
5    Fra
6    Gra
7    Hen
8    Ivy
9    Jac
Name: Name, dtype: object

### 7.7 `replace()` — Replacing Values

Replace specific values in a column or across the entire DataFrame.

In [60]:
df = pd.read_csv("students.csv")

# Replace a single value
df_replaced = df.copy()
df_replaced["Major"] = df_replaced["Major"].replace("DS", "Data Science")
print("--- Replace 'DS' with 'Data Science' ---")
print(df_replaced["Major"].value_counts())

# Replace multiple values using a dictionary
df_replaced["Major"] = df_replaced["Major"].replace({
    "Stats": "Statistics",
    "Math": "Mathematics",
})
print("\n--- Replace multiple values ---")
print(df_replaced["Major"].value_counts())

--- Replace 'DS' with 'Data Science' ---
Major
Data Science    3
Stats           3
Math            2
CS              2
Name: count, dtype: int64

--- Replace multiple values ---
Major
Data Science    3
Statistics      3
Mathematics     2
CS              2
Name: count, dtype: int64

### 7.8 `astype()` — Changing Data Types

Convert columns to a different data type. Common use cases: convert strings to numbers, integers to categories.

In [61]:
df = pd.read_csv("students.csv")

# Check current types
print("--- Original dtypes ---")
print(df.dtypes)

# Convert Age to float
df["Age_float"] = df["Age"].astype(float)
print(f"\nAge as float: {df['Age_float'].dtype}")

# Convert Major to category type (saves memory for large datasets)
df["Major_cat"] = df["Major"].astype("category")
print(f"Major as category: {df['Major_cat'].dtype}")
print(f"Categories: {df['Major_cat'].cat.categories.tolist()}")

# Convert numeric to string
df["Midterm_str"] = df["Midterm"].astype(str)
print(f"\nMidterm as string: {df['Midterm_str'].dtype}")
print(f"Example: '{df['Midterm_str'].iloc[0]}' (type: {type(df['Midterm_str'].iloc[0]).__name__})")

--- Original dtypes ---
Name       object
Age         int64
Major      object
Midterm     int64
Final       int64
dtype: object

Age as float: float64
Major as category: category
Categories: ['CS', 'DS', 'Math', 'Stats']

Midterm as string: object
Example: '85' (type: str)

---
## 8. Handling Missing Data

Real-world data almost always has **missing values**. Pandas represents them as `NaN` (Not a Number).  
Handling missing data correctly is crucial — ignoring it can lead to wrong conclusions.

### 8.1 Creating Data with Missing Values

In [62]:
# Create DataFrame with missing values
df_missing = pd.DataFrame({
    "Name":    ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Age":     [22, np.nan, 23, 22, 20],
    "Midterm": [85, 78, np.nan, 88, 76],
    "Final":   [90, 82, 88, np.nan, 80],
})
print(df_missing)

      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob   NaN     78.0   82.0
2  Charlie  23.0      NaN   88.0
3    Diana  22.0     88.0    NaN
4      Eve  20.0     76.0   80.0

### 8.2 Detecting Missing Values

`isnull()` returns a boolean DataFrame — `True` where data is missing.

In [63]:
# Detect missing values
print("--- isnull() ---")
print(df_missing.isnull())

# Count missing per column
print("\n--- Missing count per column ---")
print(df_missing.isnull().sum())

# Total missing
print(f"\nTotal missing values: {df_missing.isnull().sum().sum()}")

--- isnull() ---
    Name    Age  Midterm  Final
0  False  False    False  False
1  False   True    False  False
2  False  False     True  False
3  False  False    False   True
4  False  False    False  False

--- Missing count per column ---
Name       0
Age        1
Midterm    1
Final      1
dtype: int64

Total missing values: 3

### 8.3 Dropping Missing Values

`dropna()` removes rows (or columns) that contain missing values. Use `how` and `subset` to control the behavior.

In [64]:
# Drop rows with ANY missing value
print("--- dropna() ---")
print(df_missing.dropna())

# Drop only rows where ALL values are missing
print("\n--- dropna(how='all') ---")
print(df_missing.dropna(how="all"))

# Drop rows where specific columns are missing
print("\n--- dropna(subset=['Final']) ---")
print(df_missing.dropna(subset=["Final"]))

--- dropna() ---
    Name   Age  Midterm  Final
0  Alice  22.0     85.0   90.0
4    Eve  20.0     76.0   80.0

--- dropna(how='all') ---
      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob   NaN     78.0   82.0
2  Charlie  23.0      NaN   88.0
3    Diana  22.0     88.0    NaN
4      Eve  20.0     76.0   80.0

--- dropna(subset=['Final']) ---
      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob   NaN     78.0   82.0
2  Charlie  23.0      NaN   88.0
4      Eve  20.0     76.0   80.0

### 8.4 Filling Missing Values

Instead of dropping data, you can **fill** missing values with a replacement — mean, median, or a custom value.

In [65]:
# Fill with a fixed value
print("--- Fill with 0 ---")
print(df_missing.fillna(0))

--- Fill with 0 ---
      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob   0.0     78.0   82.0
2  Charlie  23.0      0.0   88.0
3    Diana  22.0     88.0    0.0
4      Eve  20.0     76.0   80.0

**Fill with the column mean** — a common strategy for numeric columns.

In [66]:
# Fill with column mean (only for numeric columns)
df_filled = df_missing.copy()
numeric_cols = df_filled.select_dtypes(include="number").columns
df_filled[numeric_cols] = df_filled[numeric_cols].fillna(df_filled[numeric_cols].mean())

print("--- Fill with column mean ---")
print(df_filled)

--- Fill with column mean ---
      Name    Age  Midterm  Final
0    Alice  22.00    85.00   90.0
1      Bob  21.75    78.00   82.0
2  Charlie  23.00    81.75   88.0
3    Diana  22.00    88.00   85.0
4      Eve  20.00    76.00   80.0

**Forward fill (`ffill`)** and **backward fill (`bfill`)** — useful for time series or ordered data.

In [67]:
# Forward fill (use previous value)
print("--- Forward fill ---")
print(df_missing.ffill())

# Backward fill (use next value)
print("\n--- Backward fill ---")
print(df_missing.bfill())

--- Forward fill ---
      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob  22.0     78.0   82.0
2  Charlie  23.0     78.0   88.0
3    Diana  22.0     88.0   88.0
4      Eve  20.0     76.0   80.0

--- Backward fill ---
      Name   Age  Midterm  Final
0    Alice  22.0     85.0   90.0
1      Bob  23.0     78.0   82.0
2  Charlie  23.0     88.0   88.0
3    Diana  22.0     88.0   80.0
4      Eve  20.0     76.0   80.0

---
## 9. GroupBy — Split-Apply-Combine

GroupBy is one of Pandas' most powerful operations. It follows a three-step pattern:

1. **Split** — divide the data into groups based on some criteria
2. **Apply** — apply a function to each group independently
3. **Combine** — merge the results back together

```
df.groupby("column").aggregation()
```

### 9.1 Basic GroupBy

Group students by Major and compute the mean of each numeric column.

In [68]:
df = pd.read_csv("students.csv")
df["Average"] = df["Midterm"] * 0.4 + df["Final"] * 0.6

# Group by Major → compute mean
print("--- Mean by Major ---")
print(df.groupby("Major")[["Midterm", "Final", "Average"]].mean().round(1))

--- Mean by Major ---
       Midterm  Final  Average
Major
CS        85.5   86.0     85.8
DS        84.0   91.0     88.2
Math      87.0   83.0     84.6
Stats     79.7   80.7     80.3

### 9.2 Multiple Aggregations with `agg()`

Apply **different functions** to different columns, or multiple functions to the same column.

In [70]:
# Multiple aggregation functions
result = df.groupby("Major").agg(
    Count=("Name", "count"),
    Avg_Midterm=("Midterm", "mean"),
    Avg_Final=("Final", "mean"),
    Max_Average=("Average", "max"),
    Min_Average=("Average", "min"),
).round(1)

print(result)

       Count  Avg_Midterm  Avg_Final  Max_Average  Min_Average
Major
CS         2         85.5       86.0         93.2         78.4
DS         3         84.0       91.0         92.2         84.4
Math       2         87.0       83.0         89.6         79.6
Stats      3         79.7       80.7         87.0         73.4

### 9.3 Group by Multiple Columns

In [71]:
# Group by Major AND Age
print(df.groupby(["Major", "Age"])["Average"].mean().round(1))

Major  Age
CS     20     78.4
       22     93.2
DS     22     90.1
       23     84.4
Math   21     79.6
       23     89.6
Stats  20     73.4
       21     80.4
       24     87.0
Name: Average, dtype: float64

### 9.4 Pivot Table

`pivot_table()` creates a spreadsheet-style summary table — like Excel's PivotTable. It combines groupby + reshape in one step.

In [120]:
df = pd.read_csv("students.csv")
df["Average"] = df["Midterm"] * 0.4 + df["Final"] * 0.6

# Simple pivot table: average score by Major
pivot1 = df.pivot_table(
    values="Average",     # What to summarize
    index="Major",        # Row labels
    aggfunc="mean"        # How to aggregate (default is mean)
).round(1)
print("--- Average by Major ---")
print(pivot1)

# Pivot table with multiple aggregations
pivot2 = df.pivot_table(
    values=["Midterm", "Final"],
    index="Major",
    aggfunc=["mean", "max"]
).round(1)
print("\n--- Mean and Max by Major ---")
print(pivot2)

# Pivot table with row AND column grouping + margins (totals)
pivot3 = df.pivot_table(
    values="Average",
    index="Major",
    columns="Age",
    aggfunc="mean",
    margins=True,          # Add row/column totals
    margins_name="Overall"
).round(1)
print("\n--- Average by Major × Age (with totals) ---")
print(pivot3)

--- Average by Major ---
       Average
Major
CS        85.8
DS        88.2
Math      84.6
Stats     80.3

--- Mean and Max by Major ---
       mean           max
      Final Midterm Final Midterm
Major
CS     86.0    85.5    92      95
DS     91.0    84.0    95      88
Math   83.0    87.0    88      92
Stats  80.7    79.7    85      90

--- Average by Major × Age (with totals) ---
Age        20    21    22    23    24  Overall
Major
CS       78.4   NaN  93.2   NaN   NaN     85.8
DS        NaN   NaN  90.1  84.4   NaN     88.2
Math      NaN  79.6   NaN  89.6   NaN     84.6
Stats    73.4  80.4   NaN   NaN  87.0     80.3
Overall  75.9  80.0  91.1  87.0  87.0     84.6

### 9.5 `size()` and `value_counts()`

Count the number of rows in each group.

In [121]:
# Count per group
print("--- Group sizes ---")
print(df.groupby("Major").size())

# Same thing with value_counts()
print("\n--- value_counts ---")
print(df["Major"].value_counts())

--- Group sizes ---
Major
CS       2
DS       3
Math     2
Stats    3
dtype: int64

--- value_counts ---
Major
DS       3
Stats    3
Math     2
CS       2
Name: count, dtype: int64

---
## 10. Merge & Concatenation

Combining data from multiple sources is a daily task in data analysis.

### 10.1 Concatenation with `pd.concat()`

Stack DataFrames **vertically** (add rows) or **horizontally** (add columns).

**Vertical concatenation** — combine two DataFrames with the same columns (like adding more rows).

In [122]:
# Two classes with the same columns
class_a = pd.DataFrame({
    "Name":  ["Alice", "Bob"],
    "Score": [92, 78],
})

class_b = pd.DataFrame({
    "Name":  ["Charlie", "Diana"],
    "Score": [85, 95],
})

# Vertical stack (default axis=0)
combined = pd.concat([class_a, class_b], ignore_index=True)
print("--- Vertical concat ---")
print(combined)

--- Vertical concat ---
      Name  Score
0    Alice     92
1      Bob     78
2  Charlie     85
3    Diana     95

**Horizontal concatenation** — add new columns side by side.

In [123]:
# Horizontal stack (axis=1)
names = pd.DataFrame({"Name": ["Alice", "Bob", "Charlie"]})
scores = pd.DataFrame({"Midterm": [85, 78, 92], "Final": [90, 82, 88]})

combined = pd.concat([names, scores], axis=1)
print("--- Horizontal concat ---")
print(combined)

--- Horizontal concat ---
      Name  Midterm  Final
0    Alice       85     90
1      Bob       78     82
2  Charlie       92     88

### 10.2 Merge (SQL-style Join)

`pd.merge()` combines DataFrames based on a **shared key column** — just like SQL JOIN.

| Join Type | Keeps |
|-----------|-------|
| `inner` | Only matching rows from both (default) |
| `left` | All rows from left + matches from right |
| `right` | All rows from right + matches from left |
| `outer` | All rows from both |

Let's create two separate tables and merge them on a shared key.

In [75]:
# Table 1: Student info
students = pd.DataFrame({
    "ID":    [1, 2, 3, 4, 5],
    "Name":  ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Major": ["DS", "Stats", "Math", "DS", "CS"],
})

# Table 2: Exam scores
exams = pd.DataFrame({
    "ID":      [1, 2, 3, 4, 6],
    "Midterm": [85, 78, 92, 88, 70],
    "Final":   [90, 82, 88, 95, 75],
})

print("--- students ---")
print(students)
print("\n--- exams ---")
print(exams)

--- students ---
   ID     Name  Major
0   1    Alice     DS
1   2      Bob  Stats
2   3  Charlie   Math
3   4    Diana     DS
4   5      Eve     CS

--- exams ---
   ID  Midterm  Final
0   1       85     90
1   2       78     82
2   3       92     88
3   4       88     95
4   6       70     75

Notice: Student ID 5 (Eve) has no exam scores, and ID 6 has scores but no student info. The join type determines what happens.

In [124]:
# Inner join: only IDs present in BOTH tables
inner = pd.merge(students, exams, on="ID", how="inner")
print("--- Inner join ---")
print(inner)

# Left join: keep ALL students, fill missing exams with NaN
left = pd.merge(students, exams, on="ID", how="left")
print("\n--- Left join ---")
print(left)

# Outer join: keep ALL rows from both tables
outer = pd.merge(students, exams, on="ID", how="outer")
print("\n--- Outer join ---")
print(outer)

--- Inner join ---
   ID     Name  Major  Midterm  Final
0   1    Alice     DS       85     90
1   2      Bob  Stats       78     82
2   3  Charlie   Math       92     88
3   4    Diana     DS       88     95

--- Left join ---
   ID     Name  Major  Midterm  Final
0   1    Alice     DS     85.0   90.0
1   2      Bob  Stats     78.0   82.0
2   3  Charlie   Math     92.0   88.0
3   4    Diana     DS     88.0   95.0
4   5      Eve     CS      NaN    NaN

--- Outer join ---
   ID     Name  Major  Midterm  Final
0   1    Alice     DS     85.0   90.0
1   2      Bob  Stats     78.0   82.0
2   3  Charlie   Math     92.0   88.0
3   4    Diana     DS     88.0   95.0
4   5      Eve     CS      NaN    NaN
5   6      NaN    NaN     70.0   75.0

---
## 11. Apply & Lambda

When built-in methods aren't enough, `apply()` lets you run **any function** on each row or column.

### 11.1 Apply to a Column (Series)

Apply a custom function to every value in a column — like `map()` for Series.

In [77]:
df = pd.read_csv("students.csv")
df["Average"] = df["Midterm"] * 0.4 + df["Final"] * 0.6

# Custom function
def get_grade(score):
    if score >= 90: return "A"
    elif score >= 80: return "B"
    elif score >= 70: return "C"
    elif score >= 60: return "D"
    else: return "F"

# Apply to a single column
df["Grade"] = df["Average"].apply(get_grade)
print(df[["Name", "Average", "Grade"]])

      Name  Average Grade
0    Alice     88.0     B
1      Bob     80.4     B
2  Charlie     89.6     B
3    Diana     92.2     A
4      Eve     78.4     C
5    Frank     87.0     B
6    Grace     79.6     C
7    Henry     84.4     B
8      Ivy     93.2     A
9     Jack     73.4     C

Using a **lambda function** for quick, one-line transformations.

In [ ]:
# Lambda: quick one-liner
df["Name_upper"] = df["Name"].apply(lambda x: x.upper())
df["Pass"] = df["Average"].apply(lambda x: "Yes" if x >= 60 else "No")

print(df[["Name", "Name_upper", "Average", "Pass"]])

### 11.2 Apply to Rows (`axis=1`)

Apply a function to **each row** — the function receives the entire row as a Series.

In [78]:
# Apply to each row
def student_summary(row):
    return f"{row['Name']} ({row['Major']}): {row['Average']:.0f}"

df["Summary"] = df.apply(student_summary, axis=1)
print(df["Summary"])

0        Alice (DS): 88
1       Bob (Stats): 80
2    Charlie (Math): 90
3        Diana (DS): 92
4          Eve (CS): 78
5     Frank (Stats): 87
6      Grace (Math): 80
7        Henry (DS): 84
8          Ivy (CS): 93
9      Jack (Stats): 73
Name: Summary, dtype: object

### 11.3 `map()` for Value Mapping

Use `map()` to replace values based on a dictionary — perfect for recoding categories.

In [79]:
# Map: replace values using a dictionary
major_full = {
    "DS": "Data Science",
    "Stats": "Statistics",
    "Math": "Mathematics",
    "CS": "Computer Science",
}

df["Major_Full"] = df["Major"].map(major_full)
print(df[["Name", "Major", "Major_Full"]])

      Name  Major        Major_Full
0    Alice     DS      Data Science
1      Bob  Stats        Statistics
2  Charlie   Math       Mathematics
3    Diana     DS      Data Science
4      Eve     CS  Computer Science
5    Frank  Stats        Statistics
6    Grace   Math       Mathematics
7    Henry     DS      Data Science
8      Ivy     CS  Computer Science
9     Jack  Stats        Statistics

---
## 12. Practical Example: Student Performance Analysis

Let's build a complete analysis pipeline from scratch — simulating a realistic scenario.

**Step 1:** Generate a realistic student dataset.

In [80]:
rng = np.random.default_rng(2026)
n = 50

# Generate data
names = [f"Student_{i+1:02d}" for i in range(n)]
ages = rng.integers(19, 25, size=n)
majors = rng.choice(["Data Science", "Statistics", "Mathematics", "CS"], size=n)
genders = rng.choice(["M", "F"], size=n)
midterms = rng.normal(75, 12, size=n).clip(0, 100).round(1)
finals = rng.normal(72, 15, size=n).clip(0, 100).round(1)
homework = rng.normal(80, 8, size=n).clip(0, 100).round(1)

# Introduce some missing values (realistic!)
midterms[rng.choice(n, 3, replace=False)] = np.nan
finals[rng.choice(n, 2, replace=False)] = np.nan

df = pd.DataFrame({
    "Name": names,
    "Age": ages,
    "Gender": genders,
    "Major": majors,
    "Midterm": midterms,
    "Final": finals,
    "Homework": homework,
})

print(f"Dataset shape: {df.shape}")
df.head(10)

Dataset shape: (50, 7)

         Name  Age Gender         Major  Midterm  Final  Homework
0  Student_01   24      M            CS     54.1   88.8      82.8
1  Student_02   20      F    Statistics     66.6   65.1      84.6
2  Student_03   19      M  Data Science    100.0   61.8      74.6
3  Student_04   22      M  Data Science     68.0   87.6      90.4
4  Student_05   21      M    Statistics     88.4   82.8      73.1
5  Student_06   21      M   Mathematics     80.5   92.9      65.8
6  Student_07   19      F    Statistics     73.2   75.2      91.4
7  Student_08   21      M    Statistics     67.2   96.4      76.6
8  Student_09   22      F   Mathematics     90.4   67.8      80.3
9  Student_10   21      M    Statistics     72.9   56.1      95.4

**Step 2:** Inspect the data — check for missing values and basic statistics.

In [81]:
print("=== Data Info ===")
df.info()

print("\n=== Missing Values ===")
print(df.isnull().sum())

print("\n=== Descriptive Statistics ===")
print(df.describe().round(2))

=== Data Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      50 non-null     object
 1   Age       50 non-null     int64
 2   Gender    50 non-null     object
 3   Major     50 non-null     object
 4   Midterm   47 non-null     float64
 5   Final     48 non-null     float64
 6   Homework  50 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.9+ KB

=== Missing Values ===
Name        0
Age         0
Gender      0
Major       0
Midterm     3
Final       2
Homework    0
dtype: int64

=== Descriptive Statistics ===
         Age  Midterm   Final  Homework
count  50.00    47.00   48.00     50.00
mean   21.38    74.37   74.23     80.11
std     1.64    12.94   17.43      7.84
min    19.00    47.50   35.10     50.00
25%    20.00    66.50   58.65     75.98
50%    21.00    74.70   75.25     81.20
75%    23.00    82.60   86.48     85.10
max    24.00   100.00  100.00     95.40

**Step 3:** Handle missing values — fill with the column median.

In [82]:
# Fill missing exam scores with column median
print(f"Missing before: Midterm={df['Midterm'].isnull().sum()}, Final={df['Final'].isnull().sum()}")

df["Midterm"] = df["Midterm"].fillna(df["Midterm"].median())
df["Final"] = df["Final"].fillna(df["Final"].median())

print(f"Missing after:  Midterm={df['Midterm'].isnull().sum()}, Final={df['Final'].isnull().sum()}")

Missing before: Midterm=3, Final=2
Missing after:  Midterm=0, Final=0

**Step 4:** Feature engineering — calculate weighted average and assign letter grades.

In [83]:
# Weighted average: Midterm 30%, Final 50%, Homework 20%
df["Weighted_Avg"] = (
    df["Midterm"] * 0.30 +
    df["Final"] * 0.50 +
    df["Homework"] * 0.20
).round(2)

# Letter grade
def get_grade(score):
    if score >= 90: return "A"
    elif score >= 80: return "B"
    elif score >= 70: return "C"
    elif score >= 60: return "D"
    else: return "F"

df["Grade"] = df["Weighted_Avg"].apply(get_grade)

print(df[["Name", "Midterm", "Final", "Homework", "Weighted_Avg", "Grade"]].head(10))

         Name  Midterm  Final  Homework  Weighted_Avg Grade
0  Student_01     54.1   88.8      82.8         77.19     C
1  Student_02     66.6   65.1      84.6         69.45     D
2  Student_03    100.0   61.8      74.6         75.82     C
3  Student_04     68.0   87.6      90.4         82.28     B
4  Student_05     88.4   82.8      73.1         82.54     B
5  Student_06     80.5   92.9      65.8         83.76     B
6  Student_07     73.2   75.2      91.4         77.84     C
7  Student_08     67.2   96.4      76.6         83.68     B
8  Student_09     90.4   67.8      80.3         77.08     C
9  Student_10     72.9   56.1      95.4         69.00     D

**Step 5:** Analyze grade distribution overall.

In [ ]:
# Grade distribution
grade_dist = df["Grade"].value_counts().sort_index()
print("=== Grade Distribution ===")
for grade, count in grade_dist.items():
    pct = count / len(df) * 100
    bar = "█" * count
    print(f"  {grade}: {count:>2} ({pct:>5.1f}%) {bar}")

print(f"\nClass average: {df['Weighted_Avg'].mean():.1f}")
print(f"Pass rate (≥60): {(df['Weighted_Avg'] >= 60).mean()*100:.1f}%")

**Step 6:** GroupBy analysis — compare performance across majors.

In [ ]:
# Performance by Major
major_stats = df.groupby("Major").agg(
    N=("Name", "count"),
    Avg_Score=("Weighted_Avg", "mean"),
    Std_Score=("Weighted_Avg", "std"),
    Min_Score=("Weighted_Avg", "min"),
    Max_Score=("Weighted_Avg", "max"),
).round(1)

print("=== Performance by Major ===")
print(major_stats)

**Step 7:** Grade distribution by major — cross-tabulation.

In [84]:
# Cross-tabulation: Grade vs Major
cross_tab = pd.crosstab(df["Major"], df["Grade"])
print("=== Grade Distribution by Major ===")
print(cross_tab)

=== Grade Distribution by Major ===
Grade         A  B  C  D  F
Major
CS            0  3  2  4  1
Data Science  0  3  5  2  0
Mathematics   0  5  5  3  0
Statistics    1  7  5  2  2

**Step 8:** Top performers and students at risk.

In [85]:
# Top 5 students
print("=== Top 5 Students ===")
top5 = df.nlargest(5, "Weighted_Avg")[["Name", "Major", "Weighted_Avg", "Grade"]]
print(top5.to_string(index=False))

# Students at risk (grade D or F)
at_risk = df[df["Grade"].isin(["D", "F"])][["Name", "Major", "Weighted_Avg", "Grade"]]
print(f"\n=== Students at Risk ({len(at_risk)} students) ===")
print(at_risk.sort_values("Weighted_Avg").to_string(index=False))

=== Top 5 Students ===
      Name        Major  Weighted_Avg Grade
Student_26   Statistics         91.09     A
Student_45  Mathematics         88.51     B
Student_21   Statistics         88.16     B
Student_18  Mathematics         86.91     B
Student_35 Data Science         86.29     B

=== Students at Risk (14 students) ===
      Name        Major  Weighted_Avg Grade
Student_22           CS         56.20     F
Student_20   Statistics         59.38     F
Student_31   Statistics         59.51     F
Student_38  Mathematics         60.72     D
Student_19 Data Science         60.96     D
Student_44  Mathematics         63.54     D
Student_14           CS         64.02     D
Student_12 Data Science         64.69     D
Student_11           CS         66.51     D
Student_25  Mathematics         67.63     D
Student_49           CS         68.84     D
Student_10   Statistics         69.00     D
Student_02   Statistics         69.45     D
Student_23           CS         69.93     D

**Step 9:** Correlation between exams — do Midterm scores predict Final scores?

In [86]:
# Correlation matrix
corr = df[["Midterm", "Final", "Homework", "Weighted_Avg"]].corr().round(3)
print("=== Correlation Matrix ===")
print(corr)

=== Correlation Matrix ===
              Midterm  Final  Homework  Weighted_Avg
Midterm         1.000 -0.155    -0.170         0.250
Final          -0.155  1.000    -0.073         0.902
Homework       -0.170 -0.073     1.000         0.036
Weighted_Avg    0.250  0.902     0.036         1.000

**Step 10:** Save the final results to a CSV file.

In [87]:
# Save final results
output = df[["Name", "Age", "Gender", "Major",
             "Midterm", "Final", "Homework",
             "Weighted_Avg", "Grade"]]
output.to_csv("student_grades.csv", index=False)
print(f"Saved {len(output)} records to 'student_grades.csv'")

Saved 50 records to 'student_grades.csv'

---
## 13. Summary

| # | Topic | Key Functions / Concepts |
|---|-------|------------------------|
| 1 | Series | `pd.Series()`, labeled 1D data, indexing by label or position |
| 2 | DataFrame | `pd.DataFrame()`, from dict/list/NumPy, 2D tabular data |
| 3 | File I/O | `read_csv()`, `to_csv()`, `read_excel()` — one-line I/O |
| 4 | Inspection | `head()`, `info()`, `describe()`, `value_counts()`, `shape` |
| 5 | Selection | `df[col]`, `loc[]`, `iloc[]`, boolean indexing, `query()` |
| 6 | Manipulation | Add/drop/rename columns, `sort_values()`, `nlargest()` |
| 7 | Missing Data | `isnull()`, `dropna()`, `fillna()`, `ffill()`, `bfill()` |
| 8 | GroupBy | `groupby().agg()`, split-apply-combine, `crosstab()` |
| 9 | Merge | `pd.concat()`, `pd.merge()`, inner/left/outer joins |
| 10 | Apply | `apply()`, `map()`, lambda functions for custom transforms |

---
## 14. Homework (Week 3b)

### Task 1: Data Loading & Inspection
1. Load `student_grades.csv` (the file we created in Section 12)
2. Display: shape, column names, data types, first 5 rows
3. Check for missing values
4. Show descriptive statistics (`describe()`)

### Task 2: Filtering & Selection
1. Select all students with Grade "A"
2. Select all "Data Science" majors who are 22 or older
3. Find students whose Final score is higher than their Midterm
4. Find the student with the highest Weighted_Avg in each Major

### Task 3: GroupBy Analysis
1. Calculate mean, median, and std of Weighted_Avg by Gender
2. Create a cross-tabulation of Major vs Grade
3. For each Major, find: count, mean score, best student name

### Task 4: Merge Practice
Create two DataFrames:
- `df_info`: Student Name, Email, Phone (make up 8 students)
- `df_scores`: Student Name, Quiz1, Quiz2, Quiz3 (some overlap, some not)

Perform inner, left, and outer merges. Explain the difference in results.

---
## Next Week Preview

**Week 4: Data Visualization** — Matplotlib & Seaborn:
- Line plots, bar charts, histograms, scatter plots
- Seaborn statistical plots
- Building a complete EDA (Exploratory Data Analysis) workflow

Now that you can **compute** with NumPy and **organize** with Pandas, it's time to **visualize**!

---
*Applied Statistics with Python (2026) | Week 3b | Pandas*